export default {
  C: "C",
  CSharp: "C♯",
  D: "D",
  DFlat: "D♭",
  DSharp: "D♯",
  E: "E",
  EFlat: "E♭",
  F: "F",
  FSharp: "F♯",
  G: "G",
  GFlat: "G♭",
  GSharp: "G♯",
  A: "A",
  AFlat: "A♭",
  ASharp: "A♯",
  B: "B",
  BFlat: "B♭",

  correctExcl: "Correct!",
  wrongExcl: "Wrong!",

  ABORT: "ABORT",

  lastRound: "Last Round",
  score: "Score",
  accuracy: "Accuracy",
  correct: "correct",
  wrong: "wrong",

  START: "START",
  settings: "Settings",
  ROUND_LENGTH: "ROUND LENGTH",
  NOTE_INPUT: "NOTE INPUT",
  CLEF: "CLEF",
  DIFFICULTY: "DIFFICULTY",
  ACCIDENTALS: "ACCIDENTALS",
  LANGUAGE: "LANGUAGE",
  oneMinute: "1 minute",
  fiveMinutes: "5 minutes",
  infinite: "Infinite",
  buttons: "Buttons",
  piano: "Piano",
  trebleClef: "Treble",
  bassClef: "Bass",
  both: "Both",
  easy: "Easy",
  normal: "Normal",
  hard: "Hard",
  none: "None",
  sharp: "♯",
  flat: "♭",
  sharpAndFlat: "♯ and ♭",
  SOUND: "SOUND",
  on: "On",
  off: "Off",

  TIME: "TIME",
  CORRECT: "CORRECT",
  ACCURACY: "ACCURACY",
  SCORE: "SCORE",

  record: "High Score"
};
