export default {
  C: "do",
  CSharp: "do dièse",
  D: "ré",
  DFlat: "ré bémol",
  DSharp: "ré dièse",
  E: "mi",
  EFlat: "mi bémol",
  F: "fa",
  FSharp: "fa dièse",
  G: "so",
  GFlat: "so bémol",
  GSharp: "so dièse",
  A: "la",
  AFlat: "la bémol",
  ASharp: "la dièse",
  B: "si",
  BFlat: "si bémol",

  correctExcl: "C'est juste!",
  wrongExcl: "C'est faux!",

  ABORT: "ABANDONNER LA TOURNÉE",

  lastRound: "Dernière tournée",
  score: "Points",
  accuracy: "Précision",
  correct: "juste",
  wrong: "faux",

  START: "START",
  settings: "Options",
  ROUND_LENGTH: "DURÉE DE TOURNÉE",
  NOTE_INPUT: "SAISI DE NOTES",
  CLEF: "CLÉ",
  DIFFICULTY: "DEGRÉ DE DIFFICULTÉ",
  ACCIDENTALS: "ARMATURE",
  LANGUAGE: "LANGUE",
  oneMinute: "1 minute",
  fiveMinutes: "5 minutes",
  infinite: "Infini",
  buttons: "Boutons",
  piano: "Piano",
  trebleClef: "clé de sol",
  bassClef: "clé de basse",
  both: "les deux",
  easy: "facile",
  normal: "moyen",
  hard: "difficile",
  none: "aucune",
  sharp: "♯",
  flat: "♭",
  sharpAndFlat: "♯ et ♭",
  SOUND: "SON",
  on: "activé",
  off: "désactivé",

  TIME: "TEMPS",
  CORRECT: "JUSTES",
  ACCURACY: "PRÉCISION",
  SCORE: "POINTS",

  record: "Record"
};
