export default {
    C: "do",
    CSharp: "do diesis",
    D: "re",
    DFlat: "re bemolle",
    DSharp: "re diesis",
    E: "mi",
    EFlat: "mi bemolle",
    F: "fa",
    FSharp: "fa diesis",
    G: "sol",
    GFlat: "sol bemolle",
    GSharp: "sol diesis",
    A: "la",
    AFlat: "la bemolle",
    ASharp: "la diesis",
    B: "si",
    BFlat: "si bemolle",
  
    correctExcl: "Giusto!",
    wrongExcl: "Sbagliato!",
  
    ABORT: "Esci",
  
    lastRound: "Ultimo turno",
    score: "Punti",
    accuracy: "Precisione",
    correct: "Corretto",
    wrong: "Sbagliato",
  
    START: "START",
    settings: "Opzioni",
    ROUND_LENGTH: "DURATA ROUND",
    NOTE_INPUT: "INSERIMENTO NOTE",
    CLEF: "CHIAVE",
    DIFFICULTY: "GRADO DI DIFFICOLTÀ",
    ACCIDENTALS: "ALTERAZIONI",
    LANGUAGE: "LINGUA",
    twentySeconds: "20 s",
    oneMinute: "1 min",
    fiveMinutes: "5 min",
    infinite: "Infinito",
    buttons: "Pulsanti",
    piano: "Pianoforte",
    trebleClef: "Violino",
    bassClef: "Basso",
    altoClef: "Alto",
    tenorClef: "Tenore",
    easy: "Facile",
    normal: "Medio",
    hard: "Difficile",
    none: "Nessuno",
    sharp: "♯",
    flat: "♭",
    sharpAndFlat: "♯ e ♭",
    SOUND: "SUONO",
    VIBRATION: "VIBRAZIONE",
    DISPLAYCORRECTNOTE: "VISUALIZZARE LA NOTA CORRETTA",
    on: "Si",
    off: "No",
  
    TIME: "TEMPO",
    CORRECT: "CORRETTI",
    ACCURACY: "PRECISIONE",
    SCORE: "PUNTEGGIO",
  
    record: "Record",
    history: "Storico",
  
    noMidiSupport: "Spiacente, sembrerebbe che il tuo dispositivo non supporti il MIDI",
    noDeviceFound: "Nessun dispositivo individuato. Reinserisci il dispositivo MIDI.",
    playTheNote: "Suona le note sulla tua tastiera MIDI.",
    lastNotePlayed: "Ultima nota suonata",
  };