export default {
  C: "C",
  CSharp: "C♯",
  D: "D",
  DFlat: "D♭",
  DSharp: "D♯",
  E: "E",
  EFlat: "E♭",
  F: "F",
  FSharp: "F♯",
  G: "G",
  GFlat: "G♭",
  GSharp: "G♯",
  A: "A",
  AFlat: "A♭",
  ASharp: "A♯",
  B: "B",
  BFlat: "B♭",

  correctExcl: "正解！",
  wrongExcl: "不正解",

  ABORT: "終了",

  lastRound: "以前のラウンド",
  score: "得点",
  accuracy: "正解率",
  correct: "個 正解",
  wrong: "個 不正解",

  START: "スタート",
  settings: "設定",
  ROUND_LENGTH: "ラウンドの長さ",
  NOTE_INPUT: "入力方式",
  CLEF: "音部記号",
  DIFFICULTY: "難度",
  ACCIDENTALS: "変化記号",
  LANGUAGE: "言語",
  twentySeconds: "20秒",
  oneMinute: "1分",
  fiveMinutes: "5分",
  infinite: "無限",
  buttons: "ボタン",
  piano: "ピアノ",
  trebleClef: "トレブル",
  bassClef: "バス",
  altoClef: "アルト",
  tenorClef: "テノール",
  easy: "易",
  normal: "中",
  hard: "難",
  none: "なし",
  sharp: "♯",
  flat: "♭",
  sharpAndFlat: "♯ & ♭",
  SOUND: "音声",
  on: "有",
  off: "無",

  TIME: "時間",
  CORRECT: "正解",
  ACCURACY: "正解率",
  SCORE: "得点",

  record: "最高得点",
  history: "履歴",

  noMidiSupport: "Sorry, it seems as if your device does not support MIDI.",
  noDeviceFound: "No device found. Please reconnect the MIDI device.",
  playTheNote: "Play the note on your MIDI keyboard.",
  lastNotePlayed: "Last note played",
};
