export default {
  C: "C",
  CSharp: "Cis",
  D: "D",
  DFlat: "Des",
  DSharp: "Dis",
  E: "E",
  EFlat: "Es",
  F: "F",
  FSharp: "Fis",
  G: "G",
  GFlat: "Ges",
  GSharp: "Gis",
  A: "A",
  AFlat: "As",
  ASharp: "Ais",
  B: "H",
  BFlat: "B",

  correctExcl: "Poprawna!",
  wrongExcl: "Zła!",

  ABORT: "PRZERWAĆ PARTIĘ",

  lastRound: "Ubiegła partia",
  score: "Punkty",
  accuracy: "Dokładność",
  correct: "poprawne",
  wrong: "złe",

  START: "START",
  settings: "Ustawienia",
  ROUND_LENGTH: "DŁUGOŚĆ PARTII",
  NOTE_INPUT: "METODA WEJŚCIA",
  CLEF: "KLUCZ",
  DIFFICULTY: "TRUDNOŚĆ",
  ACCIDENTALS: "ZNAKI CHROMATYCZNE",
  LANGUAGE: "JĘZYK",
  twentySeconds: "20 sekund",
  oneMinute: "1 minuta",
  fiveMinutes: "5 minut",
  buttons: "Przyciski",
  piano: "Klawiatura",
  trebleClef: "Klucz wiolinowy",
  bassClef: "Klucz basowy",
  both: "Oba",
  easy: "Łatwy",
  normal: "Normalny",
  hard: "Trudny",
  none: "Żadny",
  sharp: "♯",
  flat: "♭",
  sharpAndFlat: "♯ i ♭",

  TIME: "CZAS",
  CORRECT: "POPRAWNE",
  ACCURACY: "DOKŁADNOŚĆ",
  SCORE: "PUNKTY",

  record: "Rekord"
};
