export default {
  C: "C",
  CSharp: "♯C",
  D: "D",
  DFlat: "♭D",
  DSharp: "♯D",
  E: "E",
  EFlat: "♭E",
  F: "F",
  FSharp: "♯F",
  G: "G",
  GFlat: "♭G",
  GSharp: "♯G",
  A: "A",
  AFlat: "♭A",
  ASharp: "♯A",
  B: "B",
  BFlat: "♭B",

  correctExcl: "正确！",
  wrongExcl: "错误！",

  ABORT: "退出",

  lastRound: "上一轮",
  score: "分数",
  accuracy: "准确率",
  correct: "正确",
  wrong: "正确",

  START: "开始",
  settings: "设置",
  ROUND_LENGTH: "练习时长",
  NOTE_INPUT: "输入方式",
  CLEF: "谱号",
  DIFFICULTY: "难度",
  ACCIDENTALS: "临时变音记号",
  LANGUAGE: "语言",
  twentySeconds: "20 秒",
  oneMinute: "1 分钟",
  fiveMinutes: "5 分钟",
  infinite: "不限时",
  buttons: "按键",
  piano: "钢琴键盘",
  trebleClef: "高音谱号",
  bassClef: "低音谱号",
  altoClef: "中音谱号",
  tenorClef: "次中音谱号",
  pianoClef: "钢琴",
  easy: "简单",
  normal: "一般",
  hard: "困难",
  none: "无",
  sharp: "♯",
  flat: "♭",
  sharpAndFlat: "♯ 和 ♭",
  SOUND: "声音",
  VIBRATION: "震动",
  DISPLAYCORRECTNOTE: "展示正确答案",
  on: "开",
  off: "关",

  TIME: "时长",
  CORRECT: "正确",
  ACCURACY: "正确率",
  SCORE: "分数",

  record: "最高分",
  history: "历史",

  noMidiSupport: "抱歉，似乎没有连接 MIDI 设备。",
  noDeviceFound: "未找到设备，请尝试重新连接设备。",
  playTheNote: "演奏 MIDI 键盘上的音符。",
  lastNotePlayed: "上一个音符未演奏。",
};
